SELECT /*  */
       A.*
  FROM ALL_TAB_COLS A
 WHERE 1 = 1
--   AND A.OWNER = 'COM'
--   AND A.TABLE_NAME LIKE 'C%'
   AND A.OWNER = 'SYS' AND A.TABLE_NAME = 'ALL_TAB_COLS'
 ORDER BY A.TABLE_NAME, A.COLUMN_ID
;

SELECT /* select */
       A.OWNER
     , A.TABLE_NAME
     , A.COLUMN_NAME
     , A.DATA_TYPE
     , A.DATA_LENGTH
     , A.DATA_PRECISION
     , A.DATA_SCALE
     , A.NULLABLE
     , A.COLUMN_ID
     , A.DATA_DEFAULT
     , (SELECT L.COMMENTS FROM ALL_TAB_COMMENTS L WHERE L.OWNER = A.OWNER AND L.TABLE_NAME = A.TABLE_NAME) TABLE_COMMENTS
     , (SELECT L.COMMENTS FROM ALL_COL_COMMENTS L WHERE L.OWNER = A.OWNER AND L.TABLE_NAME = A.TABLE_NAME AND L.COLUMN_NAME = A.COLUMN_NAME) COLUMN_COMMENTS
--     , (SELECT LISTAGG(L.COLUMN_NAME, ',') WITHIN GROUP(ORDER BY L.COLUMN_NAME) FROM ALL_CONS_COLUMNS L WHERE L.OWNER = A.OWNER AND L.TABLE_NAME = A.TABLE_NAME AND L.COLUMN_NAME = A.COLUMN_NAME AND L.POSITION IS NOT NULL) PK
     , (SELECT 'Y' FROM ALL_CONS_COLUMNS L WHERE L.OWNER = A.OWNER AND EXISTS (SELECT 1 FROM ALL_CONSTRAINTS X WHERE X.OWNER = L.OWNER AND X.CONSTRAINT_TYPE = 'P' AND X.TABLE_NAME = A.TABLE_NAME AND X.CONSTRAINT_NAME = L.CONSTRAINT_NAME) AND L.COLUMN_NAME = A.COLUMN_NAME) PK
     , (SELECT 'Y' FROM ALL_CONS_COLUMNS L WHERE L.OWNER = A.OWNER AND EXISTS (SELECT 1 FROM ALL_CONSTRAINTS X WHERE X.OWNER = L.OWNER AND X.CONSTRAINT_TYPE = 'R' AND X.TABLE_NAME = A.TABLE_NAME AND X.CONSTRAINT_NAME = L.CONSTRAINT_NAME) AND L.COLUMN_NAME = A.COLUMN_NAME) FK
  FROM ALL_TAB_COLS A
 WHERE 1 = 1
   AND A.OWNER = 'COM'
--   AND A.TABLE_NAME LIKE 'C%'
--   AND A.TABLE_NAME = 'ALL_TAB_COLS'
 ORDER BY A.OWNER, A.TABLE_NAME, A.COLUMN_ID
;

--

SELECT /* select */
       A.OWNER
     , A.TABLE_NAME
     , A.COLUMN_NAME
     , A.DATA_TYPE
     , A.DATA_LENGTH
     , A.DATA_PRECISION
     , A.DATA_SCALE
     , A.NULLABLE
     , A.COLUMN_ID
     , A.DATA_DEFAULT
     , (SELECT L.COMMENTS FROM ALL_TAB_COMMENTS L WHERE L.OWNER = A.OWNER AND L.TABLE_NAME = A.TABLE_NAME) TABLE_COMMENTS
     , (SELECT L.COMMENTS FROM ALL_COL_COMMENTS L WHERE L.OWNER = A.OWNER AND L.TABLE_NAME = A.TABLE_NAME AND L.COLUMN_NAME = A.COLUMN_NAME) COLUMN_COMMENTS
     , (SELECT 'Y' FROM ALL_CONS_COLUMNS L WHERE L.OWNER = A.OWNER AND L.TABLE_NAME = A.TABLE_NAME AND L.COLUMN_NAME = A.COLUMN_NAME AND EXISTS (SELECT 1 FROM ALL_CONSTRAINTS X WHERE X.OWNER = L.OWNER AND X.CONSTRAINT_NAME = L.CONSTRAINT_NAME AND X.CONSTRAINT_TYPE = 'P' AND X.TABLE_NAME = L.TABLE_NAME)) PK
  FROM ALL_TAB_COLS A
 WHERE 1 = 1
   AND A.OWNER = 'COM'
--   AND A.TABLE_NAME = 'COMTCADMINISTCODE'
 ORDER BY A.OWNER, A.TABLE_NAME, A.COLUMN_ID
;

--
