SELECT /*  */
       A.*
  FROM ALL_TAB_COLS A
 WHERE 1 = 1
   AND A.OWNER = 'COM'
--   AND A.TABLE_NAME LIKE 'C%'
 ORDER BY A.TABLE_NAME, A.COLUMN_ID
;

SELECT /* select */
       A.OWNER
     , A.TABLE_NAME
     , A.COLUMN_NAME
     , A.DATA_TYPE
     , A.DATA_LENGTH
     , A.DATA_PRECISION
     , A.DATA_SCALE
     , A.NULLABLE
     , A.COLUMN_ID
     , A.DATA_DEFAULT
     , (SELECT L.COMMENTS FROM ALL_COL_COMMENTS L WHERE L.OWNER = A.OWNER AND L.TABLE_NAME = A.TABLE_NAME AND L.COLUMN_NAME = A.COLUMN_NAME) COLUMN_COMMENTS
  FROM ALL_TAB_COLS A
 WHERE 1 = 1
   AND A.OWNER = 'COM'
--   AND A.TABLE_NAME LIKE 'C%'
--   AND A.TABLE_NAME = 'ALL_TAB_COLS'
 ORDER BY A.OWNER, A.TABLE_NAME, A.COLUMN_ID
;
