SELECT /*  */
       A.*
  FROM ALL_TABLES A
 WHERE 1 = 1
   AND A.OWNER = 'COM'
--   AND A.TABLE_NAME LIKE 'C%'
 ORDER BY A.TABLE_NAME
;

SELECT /*  */
       A.TABLE_NAME
       , (SELECT COMMENTS FROM ALL_TAB_COMMENTS WHERE ALL_TAB_COMMENTS.OWNER = A.OWNER AND ALL_TAB_COMMENTS.TABLE_NAME = A.TABLE_NAME) TABLE_COMMENT
  FROM ALL_TABLES A
 WHERE 1 = 1
   AND A.OWNER = 'COM'
--   AND A.TABLE_NAME LIKE 'C%'
 ORDER BY A.TABLE_NAME
;
