SELECT /* select */
       A.*
  FROM ALL_TABLES A
 WHERE 1 = 1
   AND A.OWNER = 'COM'
--   AND A.TABLE_NAME LIKE 'C%'
 ORDER BY A.TABLE_NAME
;

SELECT /* select */
       A.OWNER
       , A.TABLE_NAME
       , (SELECT L.COMMENTS FROM ALL_TAB_COMMENTS L WHERE L.OWNER = A.OWNER AND L.TABLE_NAME = A.TABLE_NAME) TABLE_COMMENTS
       , (SELECT L.CONSTRAINT_NAME FROM ALL_CONSTRAINTS L WHERE L.OWNER = A.OWNER AND L.TABLE_NAME = A.TABLE_NAME AND EXISTS (SELECT 1 FROM ALL_CONSTRAINTS X WHERE X.OWNER = L.OWNER AND X.CONSTRAINT_NAME = L.CONSTRAINT_NAME AND X.CONSTRAINT_TYPE = 'P' AND X.TABLE_NAME = L.TABLE_NAME)) PK_NAME
  FROM ALL_TABLES A
 WHERE 1 = 1
--   AND A.OWNER = 'COM'
   AND A.OWNER IN (
       'COM'
     , 'COM320'
   )
 ORDER BY A.OWNER, A.TABLE_NAME
;
