SELECT /*  */
       A.*
  FROM ALL_TAB_COLS A
 WHERE 1 = 1
   AND A.OWNER = 'COM'
--   AND A.TABLE_NAME LIKE 'C%'
 ORDER BY A.TABLE_NAME, A.COLUMN_ID
;

SELECT /*  */
       A.OWNER
     , A.TABLE_NAME
     , A.COLUMN_NAME
     , A.DATA_TYPE
     , A.DATA_LENGTH
     , A.DATA_PRECISION
     , A.DATA_SCALE
     , A.NULLABLE
     , A.COLUMN_ID
     , A.DATA_DEFAULT
     , (SELECT COMMENTS FROM ALL_COL_COMMENTS WHERE ALL_COL_COMMENTS.OWNER = A.OWNER AND ALL_COL_COMMENTS.TABLE_NAME = A.TABLE_NAME AND ALL_COL_COMMENTS.COLUMN_NAME = A.COLUMN_NAME) COLUMN_COMMENT
  FROM ALL_TAB_COLS A
 WHERE 1 = 1
   AND A.OWNER = 'COM'
--   AND A.TABLE_NAME LIKE 'C%'
 ORDER BY A.TABLE_NAME, A.COLUMN_ID
;
