SELECT * FROM ALL_CONSTRAINTS X WHERE X.OWNER = 'COM'
--AND X.CONSTRAINT_TYPE = 'P'
--AND X.TABLE_NAME = 'COMTCADMINISTCODERECPTNLOG'
AND X.TABLE_NAME = 'COMTCCMMNDETAILCODE'
;

SELECT * FROM ALL_CONS_COLUMNS L WHERE L.OWNER = 'COM' AND L.TABLE_NAME = 'COMTCADMINISTCODERECPTNLOG';

SELECT * FROM ALL_CONS_COLUMNS L WHERE L.OWNER = 'COM' AND EXISTS (SELECT 1 FROM ALL_CONSTRAINTS X WHERE X.OWNER = 'COM' AND X.CONSTRAINT_TYPE = 'P' AND X.TABLE_NAME = 'COMTCADMINISTCODERECPTNLOG' AND X.CONSTRAINT_NAME = L.CONSTRAINT_NAME)
;
