SELECT /* select */
       A.*
  FROM ALL_CONSTRAINTS A
 WHERE 1 = 1
   AND A.OWNER = 'COM'
   AND A.CONSTRAINT_TYPE = 'P'
   AND A.TABLE_NAME = 'COMTCADMINISTCODE'
;

SELECT /* select */
       A.CONSTRAINT_NAME
  FROM ALL_CONSTRAINTS A
 WHERE 1 = 1
   AND A.OWNER = 'COM'
   AND A.CONSTRAINT_TYPE = 'P'
   AND A.TABLE_NAME = 'COMTCADMINISTCODE'
;
