/* 공통분류코드 */
INSERT INTO COMTCCMMNCLCODE(CL_CODE, CL_CODE_NM, CL_CODE_DC, USE_AT, FRST_REGIST_PNTTM, FRST_REGISTER_ID, LAST_UPDT_PNTTM, LAST_UPDUSR_ID) VALUES ('AAA', '관리자', '관리자', 'Y', NOW(), 'SYSTEM', NOW(), 'SYSTEM');
INSERT INTO COMTCCMMNCLCODE(CL_CODE, CL_CODE_NM, CL_CODE_DC, USE_AT, FRST_REGIST_PNTTM, FRST_REGISTER_ID, LAST_UPDT_PNTTM, LAST_UPDUSR_ID) VALUES ('AAB', '사용자', '사용자', 'Y', NOW(), 'SYSTEM', NOW(), 'SYSTEM');
