SELECT /* select */
       A.*
  FROM ALL_OBJECTS A
 WHERE 1 = 1
   AND A.OWNER = 'SYS'
--   AND A.OBJECT_NAME LIKE 'ALL_TA%'
--   AND A.OBJECT_NAME LIKE 'ALL_%COMMENTS%'
--   AND A.OBJECT_NAME LIKE 'ALL_%PK%'
   AND A.OBJECT_NAME LIKE 'ALL_%CONS%'
 ORDER BY A.OBJECT_NAME
;


SELECT * FROM ALL_TABLES A WHERE A.OWNER = 'COM' ORDER BY A.OWNER, A.TABLE_NAME;

SELECT * FROM ALL_TAB_COMMENTS A WHERE A.OWNER = 'COM' ORDER BY A.OWNER, A.TABLE_NAME;

SELECT * FROM ALL_TAB_COLS A WHERE A.OWNER = 'COM' ORDER BY A.OWNER, A.TABLE_NAME, A.COLUMN_ID;

SELECT * FROM ALL_COL_COMMENTS A WHERE A.OWNER = 'COM' ORDER BY A.OWNER, A.TABLE_NAME;

--SELECT * FROM ALL_REPKEY_COLUMNS;

SELECT * FROM ALL_CONSTRAINTS A WHERE A.OWNER = 'COM' AND A.CONSTRAINT_TYPE = 'P' AND A.TABLE_NAME = 'COMTCADMINISTCODERECPTNLOG';

SELECT * FROM ALL_CONS_COLUMNS A WHERE A.OWNER = 'COM'
--AND A.CONSTRAINT_NAME = 'COMTCADMINISTCODERECPTNLOG_PK'
--AND A.TABLE_NAME = 'COMTCADMINISTCODERECPTNLOG'
AND A.TABLE_NAME = 'COMTCCMMNDETAILCODE'
--AND A.COLUMN_NAME = 'OCCRRNC_DE'
--AND A.POSITION IS NOT NULL
;

--SELECT * FROM ALL_CONS_OBJ_COLUMNS;

--SELECT * FROM ALL_STREAMS_MESSAGE_CONSUMERS;
