SELECT /* select */
       A.*
  FROM ALL_OBJECTS A
 WHERE 1 = 1
   AND A.OWNER = 'SYS'
   AND A.OBJECT_NAME LIKE 'ALL_TA%'
--   AND A.OBJECT_NAME LIKE 'ALL_%COMMENTS%'
 ORDER BY A.OBJECT_NAME
;


SELECT * FROM ALL_TABLES A WHERE A.OWNER = 'COM' ORDER BY A.OWNER, A.TABLE_NAME;

SELECT * FROM ALL_TAB_COMMENTS A WHERE A.OWNER = 'COM' ORDER BY A.OWNER, A.TABLE_NAME;

SELECT * FROM ALL_TAB_COLS A WHERE A.OWNER = 'COM' ORDER BY A.OWNER, A.TABLE_NAME, A.COLUMN_ID;

SELECT * FROM ALL_COL_COMMENTS A WHERE A.OWNER = 'COM' ORDER BY A.OWNER, A.TABLE_NAME;
